require_relative "monkey_business/operation"
require_relative "monkey_business/pass_decider"
require_relative "monkey_business/monkey"
require_relative "monkey_business/repository"
require_relative "monkey_business/deserializer"
